### PR TITLE
Fix  #243 #245

### LINKED ISSUE #243: Tuple with Proto types
**Boa Code:**
type Td = {decl: Declaration, idx: int};

**Error:**
./compile/boa/Tupletest.java:135: error: no suitable constructor found for Declaration(Declaration)
					
this.___decl = new boa.types.Ast.Declaration(___decl); this.___idx = new Long(___idx);
                         ^
    constructor Declaration.Declaration(Builder<?>) is not applicable
      (argument mismatch; Declaration cannot be converted to Builder<?>)
    constructor Declaration.Declaration(boolean) is not applicable
      (argument mismatch; Declaration cannot be converted to boolean)
./compile/boa/Tupletest.java:138: error: no suitable constructor found for Declaration(Declaration)

this.___decl = new boa.types.Ast.Declaration(tmp.___decl); this.___idx = new Long(tmp.___idx);
	                ^
    constructor Declaration.Declaration(Builder<?>) is not applicable
      (argument mismatch; Declaration cannot be converted to Builder<?>)
    constructor Declaration.Declaration(boolean) is not applicable
      (argument mismatch; Declaration cannot be converted to boolean)

Note: ./compile/boa/Tupletest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: ./compile/boa/Tupletest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output

**Compiled Java Code:**

screen shot 2019-02-12 at 9 57 09 pm

**Corresponding String Template(BoaJava.stg):**

screen shot 2019-02-12 at 9 58 11 pm

**Reason:**
Compiled Java code is generated according to two parts:
* Method **visit(Final TupleType n)** in **CodeGeneratingVisitor.java** 
* String templates in **BoaJava.stg**

Boa types in the Boa program are based on two kinds of types: 
* Java types: long, String, etc.
* Proto types: boa.types.Ast.Declaration, boa.types.Ast.Method, etc(generated by Protocol Buffers).

From the **BoaJava.stg**, it only considers the basic Java types such as long, String, etic. So it gives a constructor copy like this: **this.___`<field>` = new `<type>`(___`<field>`)**
But for a Proto type(no constructor copy), to deep copy a instance should be like this: **this.___`<field>` = `<type>`.newBuilder(___`<field>`).build()**

**Proposed Solutions:**
1. Modify **BoaJava.stg** and **visit(Final TupleType n)** to clarify two cases: Java types and Proto types.
* It is easy and fast to solve the issue. But this way might lead to heavy works when more similar problems occur.

2. Create new classes to extend Proto classes and add a copy constructor to abstract the deep copy. 
* We can add additional targets and tasks in the build.xml to generate the new classes which would behave more like basic Java types. Not only for this time, but we might also need more features in Protocol Buffers Message

**My Current Solution:**
I choose the first one to by modifying BoaJava.stg and visit(Final TupleType n) in CodeGeneratingVisitor.java. And it works well for current testing.

* Modifies in **BoaJava.stg**: add an if statement by taking a boolean list protos.

screen shot 2019-02-12 at 10 57 17 pm

* Modifies in **visit(Final TupleType n)** in **CodeGeneratingVisitor.java**: add a boolean list by checking the component type.

screen shot 2019-02-12 at 11 01 14 pm

### PR DESCRIPTION
**Pull request by hyjorc1**

### CODE REVIEW

File: src/java/boa/compiler/visitors/CodeGeneratingVisitor.java [hunk 1]
```diff
@@ -326,13 +327,19 @@ public void visit(final TupleType n) {
 					fields.add("f" + fieldCount);
 				}
 				fieldCount++;
-				types.add(c.getType().type.toBoxedJavaType());
+				BoaType type = c.getType().type;
+				Boolean isProto = false;
```
Comment (psybers) [inline src/java/boa/compiler/visitors/CodeGeneratingVisitor.java]: these 4 lines can be simplified into: `protos.add(type instanceof BoaProtoTuple);`
